spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  test.database.replace: none

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.orm.jpa.JpaTransactionManager: trace
    org.springframework.orm.jpa.AbstractPlatformTransactionManager: trace
    org.springframework.transaction.interceptor.TransactionInterceptor: trace
    org.springframework.transaction.interceptor.TransactionAspectSupport: trace
